// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'introduction',
    ...['ai-apps', 'llm', 'embodied-ai'].map(dirName => ({type: 'autogenerated', dirName})),
  ],
};
export default sidebars;
